"""
Django settings for webpushdjango project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import json
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from shutil import copyfile

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mxxyic-3k(g_q7=r_)r=#6u@@imjdii(o=fm(ye=7*)yj$k7!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webpush',
    'push_notifications',
    'webpushdjango'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webpushdjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webpushdjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
config_path = (str(BASE_DIR)+'/config.json')
config_path = config_path.replace('\\/', '\\')
config_path = config_path.replace('//', '/')
if not os.path.exists(config_path):
    temp_path = config_path.replace('config.json', 'example.config.json')
    copyfile(temp_path, config_path)


LOCALHOST = False
LIVE_SITE_BASE_URL = ''
POST_IMAGE_BASE_DIR = ''

with open(config_path, 'r') as site_config:
    config_info = json.load(site_config)
    env_type = config_info.get('env')
    if config_info.get('local'):
        LOCALHOST = True
        ALLOWED_HOSTS = ['*']
    if env_type == 'dev':
        DEBUG = True
        ALLOWED_HOSTS = ['*']
    else:
        DEBUG = False
    active_db = config_info.get('active_db')
    if active_db:
        db_config = config_info.get(active_db)
        if db_config:
            DATABASES['default'] = config_info[active_db]

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BAjcxMOWBmY1QZesO2jNpBjUSlnANLa6L2Dyn9KEPAPWaif1qzlOFFH0e4DqzubxzfY6HzOhIWag6a6cPDtJO7Q",
    "VAPID_PRIVATE_KEY": "WV8gVjS-DIW-EOYrpKSlB2a8ol-fCWIublSVv2InQBQ",
    "VAPID_ADMIN_EMAIL": "richyafro@gmail.com"
}

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
